# permissions for end users to view pingers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pinger-viewer-role
rules:
- apiGroups:
  - ctrl.k8s.mirzakhani.me
  resources:
  - pingers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ctrl.k8s.mirzakhani.me
  resources:
  - pingers/status
  verbs:
  - get
