---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ctrl.k8s.mirzakhani.me
  resources:
  - pingers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ctrl.k8s.mirzakhani.me
  resources:
  - pingers/finalizers
  verbs:
  - update
- apiGroups:
  - ctrl.k8s.mirzakhani.me
  resources:
  - pingers/status
  verbs:
  - get
  - patch
  - update
